kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: fiap-jonathanb
  selfLink: /apis/project.openshift.io/v1/projects/fiap-jonathanb
  uid: 5c74fd68-48fb-48b7-bd38-10fb73007a69
  resourceVersion: '43725813'
  creationTimestamp: '2022-03-29T13:31:19Z'
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: ''
    openshift.io/requester: qnunzz
    openshift.io/sa.scc.mcs: 's0:c84,c14'
    openshift.io/sa.scc.supplemental-groups: 1007000000/10000
    openshift.io/sa.scc.uid-range: 1007000000/10000
  managedFields:
    - manager: cluster-policy-controller
      operation: Update
      apiVersion: v1
      time: '2022-03-29T13:31:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:openshift.io/sa.scc.mcs': {}
            'f:openshift.io/sa.scc.supplemental-groups': {}
            'f:openshift.io/sa.scc.uid-range': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: v1
      time: '2022-03-29T13:31:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/description': {}
            'f:openshift.io/display-name': {}
            'f:openshift.io/requester': {}
        'f:status':
          'f:phase': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-03-29T13:31:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:finalizers': {}
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
